import {
  Brain, FileText, Search, Plug, Globe, Link as LinkIcon, Layers, Rocket,
  BarChart3, Cloud, Monitor, Zap, FlaskConical, Satellite, Crown, Users,
  MessageCircle, MessageSquare, BookOpen, Handshake, Target, Wrench, Palette, Shield,
  Smartphone, Box, GraduationCap, Briefcase, Building2, MapPin, Home, Mail,
  ScrollText, Clock, Share2, CheckCircle, Lock, Gamepad2, Laptop, Hammer,
  Code2, Trophy, HandMetal, Cpu, Network, Workflow, Database, Server, Bot,
  Layout, Boxes, Sparkles, Activity, Wand2, Compass, Construction, AppWindow,
  User, Send, TerminalSquare, Eye, Sliders, Link2,
} from 'lucide-react'

const MAP = {
  // Specialties / cross-skills
  brain: Brain,
  'applied-ml': Brain,
  'llm': Brain,
  document: FileText,
  'file-text': FileText,
  search: Search,
  rag: Search,
  plug: Plug,
  'event-driven': Plug,
  graphql: Plug,
  mcp: Plug,
  globe: Globe,
  'open-source': Globe,
  distributed: Network,
  network: Network,
  'api-integration': Globe,
  link: LinkIcon,
  'link-2': Link2,
  langchain: Link2,
  'api-design': LinkIcon,
  layers: Layers,
  system: Layers,
  architecture: Layers,
  rocket: Rocket,
  'ci-cd': Rocket,
  deploy: Rocket,
  chart: BarChart3,
  'bar-chart': BarChart3,
  evaluation: BarChart3,
  cloud: Cloud,
  monitor: Monitor,
  desktop: Monitor,
  zap: Zap,
  'real-time': Zap,
  gpu: Cpu,
  cpu: Cpu,
  flask: FlaskConical,
  simulation: FlaskConical,
  satellite: Satellite,
  omniverse: Satellite,
  crown: Crown,
  leadership: Crown,
  users: Users,
  mentorship: Users,
  team: Users,
  message: MessageCircle,
  'message-square': MessageSquare,
  nlp: MessageSquare,
  communication: MessageCircle,
  book: BookOpen,
  learning: BookOpen,
  handshake: Handshake,
  teamwork: Handshake,
  target: Target,
  ownership: Target,
  wrench: Wrench,
  tooling: Wrench,
  palette: Palette,
  frontend: Palette,
  shield: Shield,
  auth: Shield,
  smartphone: Smartphone,
  mobile: Smartphone,
  box: Box,
  containers: Boxes,
  boxes: Boxes,
  'graduation-cap': GraduationCap,
  education: GraduationCap,
  briefcase: Briefcase,
  projects: Briefcase,
  'building-2': Building2,
  experiences: Building2,
  'map-pin': MapPin,
  location: MapPin,
  home: Home,
  mail: Mail,
  'scroll-text': ScrollText,
  scroll: ScrollText,
  clock: Clock,
  'share-2': Share2,
  social: Share2,
  'check-circle': CheckCircle,
  completionist: CheckCircle,
  lock: Lock,
  'gamepad-2': Gamepad2,
  game: Gamepad2,
  laptop: Laptop,
  skills: Laptop,
  hammer: Hammer,
  apps: Hammer,
  'code-2': Code2,
  trophy: Trophy,
  wave: HandMetal,
  workflow: Workflow,
  database: Database,
  server: Server,
  bot: Bot,
  agents: Bot,
  user: User,
  send: Send,
  terminal: TerminalSquare,
  layout: Layout,
  sparkles: Sparkles,
  activity: Activity,
  wand: Wand2,
  unreal: Wand2,
  compass: Compass,
  construction: Construction,
  'app-window': AppWindow,
  eye: Eye,
  vision: Eye,
  sliders: Sliders,
  'fine-tuning': Sliders,
}

export default function AppIcon({ name, size = 18, className = '', strokeWidth = 1.8, ...rest }) {
  if (!name) return null
  const Cmp = MAP[name] || MAP[name.toLowerCase?.()] || null
  if (!Cmp) return null
  return <Cmp size={size} strokeWidth={strokeWidth} className={className} data-icon={name} aria-hidden="true" {...rest} />
}
